version: 0.0 
os: linux 
files:
    - source: ./dist/webservice-0.0.1.tar.gz
      destination: /home/ec2-user/
    - source: ./ami/app-service.sh
      destination: /home/ec2-user/
    - source: ./ami/requirements.txt
      destination: /home/ec2-user/
file_exists_behavior: OVERWRITE

hooks:
  # BeforeInstall:
  #   - location: ./scripts/stop_server.sh
  #     timeout: 300
  #     runas: ec2-user
  AfterInstall: 
    - location: ./scripts/start_server.sh
      timeout: 300 
      runas: ec2-user
  ApplicationStart:
    - location: ./scripts/application_start.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: ./scripts/stop_server.sh
      timeout: 300
      runas: ec2-user